### PR TITLE
Implement a build process

### PR DESCRIPTION
**Pull request by SonofNun15**
Implemented a build process for set manager pro.

Also fixed the ui routing.

### CODE REVIEW

**Comment by SamGraber** [comment]
Looks good. Had a few minor comments. It's nice to have a build process in place. UI routing is also nice.

**Comment by SonofNun15** [comment]
Added support for running tests. I realized that the build process wouldn't have worked for you because I didn't check in gulpfile.js and karma.conf.js because .gitignore was ignoring *.js files. Had to remove this ignore, which is fine because we are building to a new folder now anyway.

**Comment by SonofNun15** [comment]
I didn't change the order of the firebase reference, but it probably should move before the app. Taking care of that now.

**Comment by SonofNun15** [comment]
Only final piece is that it would be nice auto inject the references in libReferences.json into index.html so we con't have to manually add our bower dependencies in two places (index.html and libReferences.json).

**Pull request merged**
